# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAdmin:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        # self.driver2 = webdriver.Chrome()
        self.vars = {}
        # self.vars2 = {}

    def teardown_method(self, method):
        self.driver.quit()
        # self.driver2.quit()

    def test_admin(self):
        self.driver.get("https://phptravels.net/admin/login.php")
        # self.driver2.get("https://phptravels.net/admin/login.php")


        self.driver.set_window_size(1920, 1053)
        # self.driver2.set_window_size(1920, 1053)

        self.driver.find_element(By.CSS_SELECTOR, "body").click()
        # self.driver2.find_element(By.CSS_SELECTOR, "body").click()

        self.driver.find_element(By.ID, "email").click()
        # self.driver2.find_element(By.ID, "email").click()

        self.driver.find_element(By.ID, "email").send_keys("admin@phptravels.com")
        # self.driver2.find_element(By.ID, "email").send_keys("admin@phptravels.com")

        time.sleep(2)
        self.driver.find_element(By.ID, "password").click()
        # self.driver2.find_element(By.ID, "password").click()

        self.driver.find_element(By.ID, "password").send_keys("demoadmin")
        # self.driver2.find_element(By.ID, "password").send_keys("demoadmin")
        time.sleep(2)

        self.driver.find_element(By.ID, "submit").click()
        # self.driver2.find_element(By.ID, "submit").click()

        time.sleep(10)
        self.driver.find_element(By.LINK_TEXT, "Modules").click()
        # self.driver2.find_element(By.LINK_TEXT, "Modules").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "checkedbox").click()
        # self.driver2.find_element(By.ID, "checkedbox").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".modules_cars > th #checkedbox").click()
        # self.driver2.find_element(By.CSS_SELECTOR, ".modules_cars > th #checkedbox").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".modules_hotels > th #checkedbox").click()
        # self.driver2.find_element(By.CSS_SELECTOR, ".modules_hotels > th #checkedbox").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".modules_hotelbeds > th #checkedbox").click()
        # self.driver2.find_element(By.CSS_SELECTOR, ".modules_hotelbeds > th #checkedbox").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".modules_agoda > th #checkedbox").click()
        # self.driver2.find_element(By.CSS_SELECTOR, ".modules_agoda > th #checkedbox").click()
        time.sleep(2)
        self.driver.get("https://phptravels.net")
        # self.driver2.get("https://phptravels.net")
        time.sleep(10)      
          
if __name__ == "__main__":
    test = TestAdmin()
    test.setup_method(None)
    try:
        test.test_admin()
    finally:
        test.teardown_method(None)
