# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLogin:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self):
        self.driver.get("https://phptravels.net/login")
        time.sleep(2)
        self.driver.set_window_size(1920, 1053)
        time.sleep(2)
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user@phptravels.com")
        time.sleep(2)
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("demouser")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#submitBTN > span").click()
        time.sleep(5)
        
if __name__ == "__main__":
    test = TestLogin()
    test.setup_method(None)
    try:
        test.test_login()
    finally:
        test.teardown_method(None)